name: C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes libglfw3-dev
    - name: configure
      run: cc -o coolbuild coolbuild.c
    - name: build
      run: ./coolbuild
